server:
  port: 8080
  context-path: /nfpt
content: http://localhost:${server.port}${server.context-path}


mybatis:
  type-aliases-package: com.css.nsfw.dp.domain
  mapper-locations: classpath:mapper/*.xml


## nfpt 数据源配置
nfpt:
 datasource:
  url: jdbc:oracle:thin:@78.12.73.44:1521:nfptdb1
  username: DB_NFGL
  password: NFPTDB_NFGL
  driverClassName: oracle.jdbc.driver.OracleDriver

## wt 数据源配置
wt:
 datasource:
  url: jdbc:oracle:thin:@78.12.73.55:1521:wsbsdb
  username: DB_CX
  password: WSBSDB_CX
  driverClassName: oracle.jdbc.driver.OracleDriver

spring:
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html